import type { Metadata } from "next";
import "../globals.css";
import { Header } from "@/components/header";
import { I18nProviderClient } from "@/locales/client";
import { ThemeProvider } from "@/providers/theme-provider";
import { LocaleSelector } from "@/components/locale-selector";
import { ThemeToggle } from "@/components/theme-toggle";
import { libreBaskerville } from "@/assets/fonts/libre-baskerville";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}>) {
  const { locale } = await params;
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${libreBaskerville.variable} antialiased`}>
        <I18nProviderClient locale={locale}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
            <LocaleSelector />
            <ThemeToggle />
          </ThemeProvider>
        </I18nProviderClient>
      </body>
    </html>
  );
}
